downstream_dependencies:
  - h1_hesc
  - intro_to_wc_modeling
  - karr_lab_build_utils
  - kinetic_datanator
  - mycoplasma_pneumoniae
  - obj_model
  - wc_kb
  - wc_lang
  - wc_sim
email_notifications:
  - jonrkarr@gmail.com
  - arthur.p.goldberg@mssm.edu
