downstream_dependencies:
- datanator
- h1_hesc
- intro_to_wc_modeling
- karr_lab_build_utils
- mycoplasma_pneumoniae
- obj_model
- rand_wc_model_gen
- wc_cli
- wc_env_manager
- wc_kb
- wc_lang
- wc_model_gen
- wc_sim
- bcforms
email_notifications:
- jonrkarr@gmail.com
- arthur.p.goldberg@mssm.edu
