name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pygit2
  - python
  - sphinx
  - pip:
    - configparser
    - git+https://github.com/KarrLab/log.git#egg=log
    - sphinx_rtd_theme
    - robpol86_sphinxcontrib_googleanalytics
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
